blank_issues_enabled: false
contact_links:
   - name: Question
     url: https://discord.com/servers/suazppuccin-907385605422448742
     about: Join our discord server for real-time answers and more!
